### ISSUE TITLE
Magento compile error

### ISSUE THREAD

**Issue by dongyi-chun** [magefan/module-crowdin-integration#1]
Hello Magefan team
This extension makes compilation error by incompatible syntax like below.

> Compilation was started.
> Repositories code generation... 1/9 [===>------------------------]  11% < 1 sec 119.0 MiBsyntax error, unexpected ')', expecting variable (T_VARIABLE)#0 /var/www/html/magento/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
> #1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
> #2 [internal function]: spl_autoload_call()
> #3 /var/www/html/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists()
> #4 /var/www/html/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass()
> #5 /var/www/html/magento/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract()
> #6 /var/www/html/magento/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList()
> #7 /var/www/html/magento/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
> #8 /var/www/html/magento/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process()
> #9 /var/www/html/magento/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute()
> #10 /var/www/html/magento/vendor/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
> #11 /var/www/html/magento/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
> #12 /var/www/html/magento/vendor/magento/framework/Console/Cli.php(115): Symfony\Component\Console\Application->doRun()
> #13 /var/www/html/magento/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun()
> #14 /var/www/html/magento/bin/magento(23): Symfony\Component\Console\Application->run()
> #15 {main}

I found that this line shouldn't have a comma in the end.
https://github.com/magefan/module-crowdin-integration/blob/main/Block/Adminhtml/System/Config/Form/Info.php#L28

I haven't fully tested but it looks like happens on php 7.4, php +8.0 looks okay.

**Comment by magefan** [comment]
@dongyi-chun , thank you for your report. The issue has been fixed https://github.com/magefan/module-crowdin-integration/commit/e629d3cb1b2148067455f9a7654d234cb399adff .

Please update the extension to version [2.0.1](https://github.com/magefan/module-crowdin-integration/releases/tag/2.0.1).
